"use client";
import{FormEvent,useCallback,useEffect,useState}from"react";
type Session={id:number;classCode:string;classTitle:string;sessionDate:string;topic?:string;status?:string;presentCount?:number;studentCount?:number};
type ClassItem={id:number;code:string;title:string};type Student={id:number;fullName:string;email:string};
const API="http://localhost:4000";
export default function AttendanceView({role,token}:{role:"student"|"teacher"|"admin";token:string}){
 const[sessions,setSessions]=useState<Session[]>([]),[classes,setClasses]=useState<ClassItem[]>([]),[students,setStudents]=useState<Student[]>([]);
 const[summary,setSummary]=useState({present:0,total:0,rate:0}),[classId,setClassId]=useState(""),[date,setDate]=useState(""),[topic,setTopic]=useState("");
 const[statuses,setStatuses]=useState<Record<number,"present"|"absent">>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,options:RequestInit={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...options.headers}});const d=await r.json();if(!r.ok)throw new Error(d.message||"Request failed.");return d},[token]);
 const load=useCallback(async()=>{try{const d=await request("/api/attendance");setSessions(d.sessions);if(d.summary)setSummary(d.summary);if(role==="teacher"){const c=await request("/api/classes");setClasses(c.classes)}}catch(e){setMessage(e instanceof Error?e.message:"Unable to load attendance.")}},[request,role]);
 useEffect(()=>{void load()},[load]);
 async function choose(id:string){setClassId(id);setStudents([]);if(!id)return;try{const d=await request(`/api/attendance/class/${id}/students`);setStudents(d.students);setStatuses(Object.fromEntries(d.students.map((s:Student)=>[s.id,"present"])))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load students.")}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const records=students.map(s=>({studentId:s.id,status:statuses[s.id]||"absent"}));const d=await request("/api/attendance",{method:"POST",body:JSON.stringify({classId:Number(classId),sessionDate:date,topic,records})});setMessage(d.message);setDate("");setTopic("");setStudents([]);setClassId("");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to record attendance.")}finally{setBusy(false)}}
 if(role==="student")return <><div className="page-title"><div><p className="eyebrow">Participation</p><h1>My attendance</h1><p>Your attendance record across enrolled classes.</p></div></div><section className="attendance"><div><span>Overall attendance</span><b>{summary.rate}%</b><small>{summary.present} present out of {summary.total} sessions</small></div></section>{message&&<div className="class-message">{message}</div>}<section className="card attendance-history">{sessions.map(s=><article key={s.id}><div><b>{s.classCode} · {s.classTitle}</b><small>{s.topic||"Class session"} · {new Date(s.sessionDate).toLocaleDateString()}</small></div><span className={s.status}>{s.status}</span></article>)}</section></>;
 return <><div className="page-title"><div><p className="eyebrow">Participation</p><h1>Record attendance</h1><p>Select a class and mark its enrolled students.</p></div></div><form className="attendance-form" onSubmit={save}><label>Class<select value={classId} onChange={e=>void choose(e.target.value)} required><option value="">Choose a class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.code} — {c.title}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)}/></label>{students.length>0&&<div className="roster">{students.map(s=><article key={s.id}><div><b>{s.fullName}</b><small>{s.email}</small></div><select value={statuses[s.id]} onChange={e=>setStatuses({...statuses,[s.id]:e.target.value as "present"|"absent"})}><option value="present">Present</option><option value="absent">Absent</option></select></article>)}</div>}<button className="primary" disabled={busy||!students.length}>{busy?"Saving…":"Save attendance"}</button></form>{message&&<div className="class-message">{message}</div>}<section className="card attendance-history">{sessions.map(s=><article key={s.id}><div><b>{s.classCode} · {s.classTitle}</b><small>{s.topic||"Class session"} · {new Date(s.sessionDate).toLocaleDateString()}</small></div><span>{s.presentCount}/{s.studentCount} present</span></article>)}</section></>
}