"use client";import{FormEvent,useCallback,useEffect,useState}from"react";
const API="http://localhost:4000";type D={id:number;classCode:string;title:string;content:string;authorName:string;replyCount:number;createdAt:string};type C={id:number;code:string;title:string};type R={id:number;content:string;authorName:string;createdAt:string};
export default function DiscussionView({token}:{token:string}){const[items,setItems]=useState<D[]>([]),[classes,setClasses]=useState<C[]>([]),[selected,setSelected]=useState<D|null>(null),[replies,setReplies]=useState<R[]>([]),[classId,setClassId]=useState(""),[title,setTitle]=useState(""),[content,setContent]=useState(""),[reply,setReply]=useState(""),[show,setShow]=useState(false),[message,setMessage]=useState("");
const request=useCallback(async(p:string,o:RequestInit={})=>{const r=await fetch(API+p,{...o,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.message);return d},[token]);
const load=useCallback(async()=>{try{setItems((await request("/api/discussions")).discussions);setClasses((await request("/api/classes")).classes)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load.")}},[request]);useEffect(()=>{void load()},[load]);
async function post(e:FormEvent){e.preventDefault();try{const d=await request("/api/discussions",{method:"POST",body:JSON.stringify({classId:Number(classId),title,content})});setMessage(d.message);setShow(false);setTitle("");setContent("");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to post.")}}
async function open(d:D){try{const x=await request(`/api/discussions/${d.id}`);setSelected(x.discussion);setReplies(x.replies)}catch(e){setMessage(e instanceof Error?e.message:"Unable to open.")}}
async function respond(e:FormEvent){e.preventDefault();if(!selected)return;try{const d=await request(`/api/discussions/${selected.id}/replies`,{method:"POST",body:JSON.stringify({content:reply})});setMessage(d.message);setReply("");await open(selected)}catch(e){setMessage(e instanceof Error?e.message:"Unable to reply.")}}
if(selected)return <><button className="back-link" onClick={()=>setSelected(null)}>← Discussions</button><section className="discussion-thread"><em>{selected.classCode}</em><h1>{selected.title}</h1><small>{selected.authorName} · {new Date(selected.createdAt).toLocaleString()}</small><p>{selected.content}</p></section><div className="reply-list">{replies.map(r=><article key={r.id}><b>{r.authorName}</b><p>{r.content}</p><small>{new Date(r.createdAt).toLocaleString()}</small></article>)}</div><form className="reply-form" onSubmit={respond}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…" required/><button className="primary">Post reply</button></form></>;
return <><div className="page-title"><div><p className="eyebrow">Class community</p><h1>Discussion board</h1><p>Ask questions and exchange ideas with your classes.</p></div><button className="primary" onClick={()=>setShow(!show)}>{show?"Cancel":"+ New discussion"}</button></div>{show&&<form className="discussion-form" onSubmit={post}><select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Choose class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.code} — {c.title}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Topic title" required/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Write your question or message…" required/><button className="primary">Post discussion</button></form>}{message&&<div className="class-message">{message}</div>}<section className="card discussion-list">{items.map(d=><article key={d.id} onClick={()=>open(d)}><span className="avatar">{d.authorName.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><em>{d.classCode}</em><h3>{d.title}</h3><p>{d.content}</p><small>{d.authorName} · {d.replyCount} replies</small></div></article>)}</section></>}